sudo: false
language: ruby
cache: bundler
rvm:
#  - 2.3.1
  - 2.5.3
bundler_args: --without development
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - s3cmd
install:
  - pip install --user awscli
  - gem install bundler
#  - gem install html-proofer
  - bundle install
script:
  - if [[ $TRAVIS_BRANCH == "master" ]];
    then JEKYLL_ENV=production bundle exec jekyll build --config _config.yml;
    else bundle exec jekyll build --config _config.yml --future --drafts;
    fi
#  - htmlproofer ./_site --allow-hash-href --assume-extension --url-ignore "/localhost/" --http-status-ignore "999" --disable-external
#  - htmlproofer ./_site --url-ignore "/www.edge-cloud.net/,/www.linkedin.com/" --disable-external --url-ignore "/#.*/"
deploy:
  - provider: s3
    region: us-west-2
    acl: public_read
    bucket: www.edge-cloud.net
    local_dir: _site
    cache_control:
      - "max-age=2592000":
        - "*.css"
        - ".js"
        - "*.png"
        - ".jpg"
      - "no-cache"
    # expires: "2030-12-31 00:00:00 -0000"
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
    on:
      branch: master
  - provider: pages
    local-dir: _site
    repo: edge-cloud/edge-cloud.github.io
    target-branch: master
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    on:
      branch: dev
after_deploy:
  - s3cmd ls
  - if [[ $TRAVIS_BRANCH == "master" ]]; then aws configure set preview.cloudfront true; fi
  - if [[ $TRAVIS_BRANCH == "master" ]]; then aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"; fi
