language: ruby
rvm:
  - 2.3.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
install:
  - sudo pip install awscli
  - gem install jekyll
  - gem install bundler
  - gem install mdl
  - gem install html-proofer
  - gem install rdiscount
  - bundle install
script:
  - if [[ $TRAVIS_BRANCH == "master" ]];
    then JEKYLL_ENV=production bundle exec jekyll build --config _config.yml;
    else bundle exec jekyll build --config _config.yml --future --drafts;
    fi
#  - mdl -r ~MD002,~MD013,~MD033 ./_posts
#  - htmlproofer ./_site --url-ignore "/www.edge-cloud.net/,/www.linkedin.com/" --disable-external --url-ignore "/#.*/"
deploy:
  - provider: s3
    region: us-west-2
    acl: public_read
    bucket: www.edge-cloud.net
    local_dir: _site
    cache_control:
      - "max-age=2592000":
        - "*.css"
        - ".js"
        - "*.png"
        - ".jpg"
      - "no-cache"
    # expires: "2030-12-31 00:00:00 -0000"
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
    on:
      branch: master
  - provider: pages
    local-dir: _site
    repo: edge-cloud/edge-cloud.github.io
    target-branch: master
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    on:
      branch: dev
after_deploy:
  - if [[ $TRAVIS_BRANCH == "master" ]]; then aws configure set preview.cloudfront true; fi
  - if [[ $TRAVIS_BRANCH == "master" ]]; then aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"; fi
