name: Jekyll site CI to Github Pages

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: "Set up Ruby"
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
        bundler-cache: true
        
    - name: "Install Ubuntu dependencies"
      run: |
            sudo apt-get install -y webp

    - name: "Clone Site from GitHub pages"
      run: |
            git clone https://github.com/edge-cloud/edge-cloud.github.io.git ./_site
      if: "!contains(github.event.head_commit.message, '[rebuild images]')"

    - name: "Build Jekyll site"
      run: bundle exec jekyll build --config _config.yml --future --drafts
        
    - name: "Convert Webp images"
      run: |
            chmod +x ./_build/webp-convert.sh
            ./_build/webp-convert.sh ./_site/content
      shell: bash
            
    - name: "Deploy to GitHub pages"
      run: |
            cd ./_site
            git add -A
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m 'deploy'
            git push --force https://${{ secrets.EDGECLOUD_GITHUB_TOKEN }}@github.com/edge-cloud/edge-cloud.github.io.git

      
    
